"""
ATDD Acceptance Tests — Story 1.1: Docker Compose Service Startup (AC1)

TDD RED PHASE — All tests marked pytest.mark.skip() and will FAIL until story is implemented.

Acceptance Criterion covered:
  AC1: Given a fresh clone, when I run docker-compose up, Then:
    - Postgres starts on port 5432
    - FastAPI (dqs-serve) starts on port 8000
    - Vite dev server (dqs-dashboard) starts on port 5173

These are integration-level tests that verify the docker-compose configuration
produces running services on the expected ports.

Note: These tests verify configuration correctness, not runtime behaviour.
      Runtime smoke tests are deferred to story 1-2 (environment validation).

Generated by: BMad TEA Agent (bmad-testarch-atdd)
Date: 2026-04-03
Story ID: 1-1-initialize-project-structure-development-environment
"""

import os
import subprocess
import time

import pytest
import yaml

PROJECT_ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "../.."))


def path(*parts: str) -> str:
    return os.path.join(PROJECT_ROOT, *parts)


# ===========================================================================
# AC1 — Docker Compose YAML validation (fast, no Docker required)
# ===========================================================================


class TestDockerComposeYamlValidity:
    """[P0] Validate docker-compose.yml structure before any container is started."""

    def _load_compose(self) -> dict:
        compose_path = path("docker-compose.yml")
        assert os.path.isfile(compose_path), "docker-compose.yml not found"
        with open(compose_path, "r") as f:
            return yaml.safe_load(f)

    def test_compose_file_is_valid_yaml(self) -> None:
        """[P0] docker-compose.yml must be valid YAML."""
        # THIS TEST WILL FAIL — current compose file missing services
        compose = self._load_compose()
        assert compose is not None, "docker-compose.yml is empty or invalid YAML"
        assert "services" in compose, "docker-compose.yml must have a 'services' key"

    def test_compose_defines_exactly_three_services(self) -> None:
        """[P0] docker-compose.yml must define exactly: postgres, serve, dashboard."""
        # THIS TEST WILL FAIL — serve and dashboard services not yet added
        compose = self._load_compose()
        services = compose.get("services", {})
        service_names = set(services.keys())
        required_services = {"postgres", "serve", "dashboard"}
        missing = required_services - service_names
        assert not missing, (
            f"docker-compose.yml missing required services: {missing}. "
            f"Current services: {service_names}"
        )

    def test_postgres_uses_postgres_15_image(self) -> None:
        """[P0] Postgres service must use postgres:15 image."""
        # THIS TEST WILL FAIL — could pass but validating image version
        compose = self._load_compose()
        postgres = compose.get("services", {}).get("postgres", {})
        image = postgres.get("image", "")
        assert "postgres:15" in image, (
            f"Postgres must use 'postgres:15' image, got '{image}'"
        )

    def test_serve_service_builds_from_dqs_serve(self) -> None:
        """[P0] 'serve' service must build from ./dqs-serve (Dockerfile in component dir)."""
        # THIS TEST WILL FAIL — serve service not yet added
        compose = self._load_compose()
        serve = compose.get("services", {}).get("serve", {})
        build = serve.get("build", "")

        # Accept both string "./dqs-serve" and dict {"context": "./dqs-serve"}
        if isinstance(build, dict):
            build_context = build.get("context", "")
        else:
            build_context = build

        assert "dqs-serve" in str(build_context), (
            f"'serve' service must build from ./dqs-serve, got build={build}. "
            f"Do NOT reuse serve-api/ — that is the prototype directory."
        )

    def test_serve_service_has_database_url_env(self) -> None:
        """[P0] 'serve' service must have DATABASE_URL environment variable."""
        # THIS TEST WILL FAIL — serve service not yet added
        compose = self._load_compose()
        serve = compose.get("services", {}).get("serve", {})
        env = serve.get("environment", {})

        if isinstance(env, list):
            env_keys = [e.split("=")[0] for e in env]
        else:
            env_keys = list(env.keys())

        assert "DATABASE_URL" in env_keys, (
            f"serve service must have DATABASE_URL env var. "
            f"Current env vars: {env_keys}"
        )

    def test_dashboard_service_builds_from_dqs_dashboard(self) -> None:
        """[P0] 'dashboard' service must build/run from ./dqs-dashboard."""
        # THIS TEST WILL FAIL — dashboard service not yet added
        compose = self._load_compose()
        dashboard = compose.get("services", {}).get("dashboard", {})
        build = dashboard.get("build", "")

        if isinstance(build, dict):
            build_context = build.get("context", "")
        else:
            build_context = build

        assert "dqs-dashboard" in str(build_context), (
            f"'dashboard' service must build from ./dqs-dashboard, got build={build}"
        )

    def test_compose_validate_command_exits_successfully(self) -> None:
        """[P0] `docker compose config` must exit 0 (valid compose configuration)."""
        # THIS TEST WILL FAIL — docker-compose.yml references services not yet created
        result = subprocess.run(
            ["docker", "compose", "-f", path("docker-compose.yml"), "config"],
            cwd=PROJECT_ROOT,
            capture_output=True,
            text=True,
            timeout=30,
        )
        assert result.returncode == 0, (
            f"docker compose config failed with exit code {result.returncode}. "
            f"stderr: {result.stderr[:500]}"
        )


# ===========================================================================
# AC1 — Service health checks (requires docker-compose up, slow tests)
# ===========================================================================


@pytest.mark.integration
class TestDockerComposeServiceStartup:
    """[P0] Verify docker-compose up starts all services on correct ports.

    SLOW TEST: These tests require running services via docker-compose.
    Run with: pytest tests/acceptance/test_story_1_1_docker_compose_startup.py -m integration
    """

    @pytest.fixture(scope="class", autouse=True)
    def docker_services(self) -> None:
        """Start docker-compose services and wait for them to be ready."""
        # THIS FIXTURE WILL FAIL — services don't exist yet
        subprocess.run(
            ["docker", "compose", "-f", path("docker-compose.yml"), "up", "-d"],
            cwd=PROJECT_ROOT,
            check=True,
            timeout=120,
        )
        # Wait for services to be healthy
        time.sleep(15)
        yield
        # Teardown: stop services
        subprocess.run(
            ["docker", "compose", "-f", path("docker-compose.yml"), "down"],
            cwd=PROJECT_ROOT,
            timeout=60,
        )

    def test_postgres_is_reachable_on_port_5432(self) -> None:
        """[P0] Postgres must accept connections on port 5432 after docker-compose up."""
        # THIS TEST WILL FAIL — service not yet started
        import socket

        with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s:
            s.settimeout(5)
            result = s.connect_ex(("localhost", 5432))
        assert result == 0, (
            "Postgres is not accepting connections on port 5432. "
            "Check docker-compose.yml postgres service port mapping."
        )

    def test_fastapi_health_endpoint_returns_200(self) -> None:
        """[P0] FastAPI (dqs-serve) must respond on port 8000 with GET /health -> 200."""
        # THIS TEST WILL FAIL — dqs-serve not yet built/deployed
        import urllib.error
        import urllib.request

        try:
            with urllib.request.urlopen("http://localhost:8000/health", timeout=10) as resp:
                status = resp.status
                body = resp.read().decode()
        except urllib.error.URLError as e:
            pytest.fail(
                f"FastAPI not responding on port 8000: {e}. "
                f"Expected GET /health to return 200 OK."
            )

        assert status == 200, f"Expected status 200, got {status}. Body: {body}"
        import json
        data = json.loads(body)
        assert data.get("status") == "ok", (
            f"Expected {{\"status\": \"ok\"}}, got {data}"
        )

    def test_vite_dev_server_responds_on_port_5173(self) -> None:
        """[P0] Vite dev server (dqs-dashboard) must respond on port 5173."""
        # THIS TEST WILL FAIL — dqs-dashboard not yet built/deployed
        import urllib.error
        import urllib.request

        try:
            with urllib.request.urlopen("http://localhost:5173", timeout=10) as resp:
                status = resp.status
        except urllib.error.URLError as e:
            pytest.fail(
                f"Vite dev server not responding on port 5173: {e}. "
                f"Expected dashboard to be available at http://localhost:5173."
            )

        assert status == 200, (
            f"Vite dev server returned status {status}, expected 200."
        )
