"""
ATDD Acceptance Tests — Story 1.1: Initialize Project Structure & Development Environment

TDD RED PHASE — All tests marked pytest.mark.skip() and will FAIL until story is implemented.

Acceptance Criteria covered:
  AC1: docker-compose up starts Postgres:5432, FastAPI:8000, Vite:5173
  AC2: dqs-spark has Maven structure with pom.xml and Spark as 'provided' dependency
  AC3: dqs-orchestrator has Python project with pyproject.toml and its own config/
  AC4: Each component has own config/, dependencies, build — no shared resources

Generated by: BMad TEA Agent (bmad-testarch-atdd)
Date: 2026-04-03
Story ID: 1-1-initialize-project-structure-development-environment
"""

import os
import xml.etree.ElementTree as ET

import yaml

# ---------------------------------------------------------------------------
# Project root resolution
# ---------------------------------------------------------------------------

PROJECT_ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "../.."))


def path(*parts: str) -> str:
    """Return an absolute path under PROJECT_ROOT."""
    return os.path.join(PROJECT_ROOT, *parts)


# ===========================================================================
# AC2 — dqs-spark Maven project structure
# ===========================================================================


class TestDqsSparkStructure:
    """[P0] dqs-spark must have a valid Maven project structure."""

    def test_dqs_spark_root_directory_exists(self) -> None:
        """[P0] dqs-spark/ directory must exist at project root."""
        # THIS TEST WILL FAIL — dqs-spark/ not yet created
        assert os.path.isdir(path("dqs-spark")), (
            "dqs-spark/ directory not found. "
            "Run: create pom.xml manually or use mvn archetype:generate"
        )

    def test_pom_xml_exists(self) -> None:
        """[P0] dqs-spark/pom.xml must exist."""
        # THIS TEST WILL FAIL — pom.xml not yet created
        assert os.path.isfile(path("dqs-spark", "pom.xml")), (
            "dqs-spark/pom.xml not found"
        )

    def test_pom_xml_group_id_is_com_bank_dqs(self) -> None:
        """[P0] pom.xml groupId must be 'com.bank.dqs' (NOT 'com.dqs')."""
        # THIS TEST WILL FAIL — pom.xml not yet created
        pom_path = path("dqs-spark", "pom.xml")
        assert os.path.isfile(pom_path), "dqs-spark/pom.xml not found"

        tree = ET.parse(pom_path)
        ns = {"mvn": "http://maven.apache.org/POM/4.0.0"}
        root = tree.getroot()
        group_id = root.findtext("mvn:groupId", namespaces=ns)
        assert group_id == "com.bank.dqs", (
            f"groupId must be 'com.bank.dqs', got '{group_id}'. "
            "The old prototype uses 'com.dqs' — do NOT copy it."
        )

    def test_pom_xml_artifact_id_is_dqs_spark(self) -> None:
        """[P0] pom.xml artifactId must be 'dqs-spark'."""
        # THIS TEST WILL FAIL — pom.xml not yet created
        pom_path = path("dqs-spark", "pom.xml")
        assert os.path.isfile(pom_path), "dqs-spark/pom.xml not found"

        tree = ET.parse(pom_path)
        ns = {"mvn": "http://maven.apache.org/POM/4.0.0"}
        root = tree.getroot()
        artifact_id = root.findtext("mvn:artifactId", namespaces=ns)
        assert artifact_id == "dqs-spark", (
            f"artifactId must be 'dqs-spark', got '{artifact_id}'"
        )

    def test_spark_dependency_is_provided_scope(self) -> None:
        """[P0] Spark dependency must use 'provided' scope — never bundled in fat JAR."""
        # THIS TEST WILL FAIL — pom.xml not yet created
        pom_path = path("dqs-spark", "pom.xml")
        assert os.path.isfile(pom_path), "dqs-spark/pom.xml not found"

        tree = ET.parse(pom_path)
        ns = {"mvn": "http://maven.apache.org/POM/4.0.0"}
        root = tree.getroot()

        spark_dep = None
        for dep in root.findall(".//mvn:dependency", namespaces=ns):
            artifact = dep.findtext("mvn:artifactId", namespaces=ns) or ""
            if "spark" in artifact.lower():
                spark_dep = dep
                break

        assert spark_dep is not None, "No Spark dependency found in pom.xml"
        scope = spark_dep.findtext("mvn:scope", namespaces=ns)
        assert scope == "provided", (
            f"Spark dependency scope must be 'provided', got '{scope}'. "
            "Bundling Spark into the fat JAR will cause classpath conflicts."
        )

    def test_pom_xml_spark_version_is_3_5_0(self) -> None:
        """[P0] Spark version must be exactly 3.5.0."""
        # THIS TEST WILL FAIL — pom.xml not yet created
        pom_path = path("dqs-spark", "pom.xml")
        assert os.path.isfile(pom_path), "dqs-spark/pom.xml not found"

        tree = ET.parse(pom_path)
        ns = {"mvn": "http://maven.apache.org/POM/4.0.0"}
        root = tree.getroot()

        # Check properties section for spark.version
        spark_version = root.findtext("mvn:properties/mvn:spark.version", namespaces=ns)
        if spark_version is None:
            # Might be inline in the dependency
            for dep in root.findall(".//mvn:dependency", namespaces=ns):
                artifact = dep.findtext("mvn:artifactId", namespaces=ns) or ""
                if "spark" in artifact.lower():
                    spark_version = dep.findtext("mvn:version", namespaces=ns)
                    break

        assert spark_version == "3.5.0", (
            f"Spark version must be '3.5.0', got '{spark_version}'"
        )

    def test_pom_xml_surefire_uses_java_21_jvm(self) -> None:
        """[P0] Maven Surefire must configure Java 21 JVM path for Spark test compatibility."""
        # THIS TEST WILL FAIL — pom.xml not yet created
        pom_path = path("dqs-spark", "pom.xml")
        assert os.path.isfile(pom_path), "dqs-spark/pom.xml not found"

        with open(pom_path, "r") as f:
            content = f.read()

        assert "/usr/lib/jvm/java-21-openjdk-amd64/bin/java" in content, (
            "Surefire must specify <jvm>/usr/lib/jvm/java-21-openjdk-amd64/bin/java</jvm>. "
            "Java 25 removed Subject.getSubject() used by Hadoop UGI / Spark."
        )

    def test_pom_xml_surefire_has_add_opens_flags(self) -> None:
        """[P0] Maven Surefire must include --add-opens JVM flags for Spark module access."""
        # THIS TEST WILL FAIL — pom.xml not yet created
        pom_path = path("dqs-spark", "pom.xml")
        assert os.path.isfile(pom_path), "dqs-spark/pom.xml not found"

        with open(pom_path, "r") as f:
            content = f.read()

        required_flags = [
            "--add-opens=java.base/java.lang=ALL-UNNAMED",
            "--add-opens=java.base/java.lang.invoke=ALL-UNNAMED",
            "--add-opens=java.base/java.lang.reflect=ALL-UNNAMED",
            "--add-opens=java.base/java.io=ALL-UNNAMED",
            "--add-opens=java.base/java.net=ALL-UNNAMED",
            "--add-opens=java.base/java.nio=ALL-UNNAMED",
            "--add-opens=java.base/java.util=ALL-UNNAMED",
            "--add-opens=java.base/java.util.concurrent=ALL-UNNAMED",
            "--add-opens=java.base/java.util.concurrent.atomic=ALL-UNNAMED",
            "--add-opens=java.base/sun.nio.ch=ALL-UNNAMED",
            "--add-opens=java.base/sun.nio.cs=ALL-UNNAMED",
            "--add-opens=java.base/sun.util.calendar=ALL-UNNAMED",
        ]
        missing = [flag for flag in required_flags if flag not in content]
        assert not missing, (
            f"pom.xml Surefire is missing {len(missing)} required --add-opens flags: "
            f"{missing[:3]}... (copy from spark-job/pom.xml)"
        )

    def test_dqs_spark_main_java_directory_structure(self) -> None:
        """[P0] dqs-spark must have Maven standard src/main/java/com/bank/dqs/ layout."""
        # THIS TEST WILL FAIL — directories not yet created
        base = path("dqs-spark", "src", "main", "java", "com", "bank", "dqs")
        assert os.path.isdir(base), f"Directory not found: {base}"

        required_subdirs = ["checks", "scanner", "model", "writer"]
        for subdir in required_subdirs:
            assert os.path.isdir(os.path.join(base, subdir)), (
                f"Missing subdirectory: src/main/java/com/bank/dqs/{subdir}/"
            )

    def test_dqs_spark_test_java_directory_exists(self) -> None:
        """[P0] dqs-spark must have src/test/java/com/bank/dqs/ test directory."""
        # THIS TEST WILL FAIL — directories not yet created
        test_dir = path("dqs-spark", "src", "test", "java", "com", "bank", "dqs")
        assert os.path.isdir(test_dir), (
            f"Test directory not found: {test_dir}"
        )

    def test_dqs_spark_placeholder_main_class_exists(self) -> None:
        """[P0] dqs-spark must have DqsJob.java placeholder main class."""
        # THIS TEST WILL FAIL — file not yet created
        job_file = path("dqs-spark", "src", "main", "java", "com", "bank", "dqs", "DqsJob.java")
        assert os.path.isfile(job_file), "DqsJob.java not found"

        with open(job_file, "r") as f:
            content = f.read()
        assert "package com.bank.dqs" in content, (
            "DqsJob.java must declare 'package com.bank.dqs'"
        )

    def test_dqs_spark_config_directory_exists(self) -> None:
        """[P1] dqs-spark must have its own config/ directory (self-containment)."""
        # THIS TEST WILL FAIL — directory not yet created
        config_dir = path("dqs-spark", "config")
        assert os.path.isdir(config_dir), (
            "dqs-spark/config/ not found. "
            "Each component must have its own config/ — no shared root config."
        )

    def test_dqs_spark_application_properties_exists(self) -> None:
        """[P1] dqs-spark/config/application.properties must exist with placeholder DB config."""
        # THIS TEST WILL FAIL — file not yet created
        props_file = path("dqs-spark", "config", "application.properties")
        assert os.path.isfile(props_file), (
            "dqs-spark/config/application.properties not found"
        )


# ===========================================================================
# AC3 — dqs-orchestrator Python project structure
# ===========================================================================


class TestDqsOrchestratorStructure:
    """[P0] dqs-orchestrator must have a valid Python/uv project structure."""

    def test_dqs_orchestrator_root_directory_exists(self) -> None:
        """[P0] dqs-orchestrator/ directory must exist at project root."""
        # THIS TEST WILL FAIL — dqs-orchestrator/ not yet created
        assert os.path.isdir(path("dqs-orchestrator")), (
            "dqs-orchestrator/ not found. Run: uv init dqs-orchestrator"
        )

    def test_dqs_orchestrator_pyproject_toml_exists(self) -> None:
        """[P0] dqs-orchestrator/pyproject.toml must exist (uv-managed project)."""
        # THIS TEST WILL FAIL — pyproject.toml not yet created
        assert os.path.isfile(path("dqs-orchestrator", "pyproject.toml")), (
            "dqs-orchestrator/pyproject.toml not found. "
            "Use 'uv init dqs-orchestrator', NOT pip/requirements.txt"
        )

    def test_dqs_orchestrator_has_psycopg2_dependency(self) -> None:
        """[P0] dqs-orchestrator must declare psycopg2-binary dependency."""
        # THIS TEST WILL FAIL — pyproject.toml not yet created
        pyproject_path = path("dqs-orchestrator", "pyproject.toml")
        assert os.path.isfile(pyproject_path), "pyproject.toml not found"

        with open(pyproject_path, "r") as f:
            content = f.read()
        assert "psycopg2-binary" in content, (
            "dqs-orchestrator/pyproject.toml must declare psycopg2-binary dependency"
        )

    def test_dqs_orchestrator_has_pyyaml_dependency(self) -> None:
        """[P0] dqs-orchestrator must declare pyyaml dependency."""
        # THIS TEST WILL FAIL — pyproject.toml not yet created
        pyproject_path = path("dqs-orchestrator", "pyproject.toml")
        assert os.path.isfile(pyproject_path), "pyproject.toml not found"

        with open(pyproject_path, "r") as f:
            content = f.read()
        assert "pyyaml" in content, (
            "dqs-orchestrator/pyproject.toml must declare pyyaml dependency"
        )

    def test_dqs_orchestrator_config_directory_exists(self) -> None:
        """[P0] dqs-orchestrator must have its own config/ directory."""
        # THIS TEST WILL FAIL — config/ not yet created
        assert os.path.isdir(path("dqs-orchestrator", "config")), (
            "dqs-orchestrator/config/ not found. "
            "AC3 requires orchestrator to have its own config/ directory."
        )

    def test_dqs_orchestrator_config_orchestrator_yaml_exists(self) -> None:
        """[P0] dqs-orchestrator/config/orchestrator.yaml must exist."""
        # THIS TEST WILL FAIL — file not yet created
        assert os.path.isfile(path("dqs-orchestrator", "config", "orchestrator.yaml")), (
            "dqs-orchestrator/config/orchestrator.yaml not found"
        )

    def test_dqs_orchestrator_config_parent_paths_yaml_exists(self) -> None:
        """[P0] dqs-orchestrator/config/parent_paths.yaml must exist."""
        # THIS TEST WILL FAIL — file not yet created
        assert os.path.isfile(path("dqs-orchestrator", "config", "parent_paths.yaml")), (
            "dqs-orchestrator/config/parent_paths.yaml not found"
        )

    def test_dqs_orchestrator_src_package_exists(self) -> None:
        """[P0] dqs-orchestrator must have src/orchestrator/ Python package."""
        # THIS TEST WILL FAIL — directories not yet created
        pkg_dir = path("dqs-orchestrator", "src", "orchestrator")
        assert os.path.isdir(pkg_dir), f"src/orchestrator/ package not found: {pkg_dir}"

    def test_dqs_orchestrator_src_init_exists(self) -> None:
        """[P0] src/orchestrator/__init__.py must exist."""
        # THIS TEST WILL FAIL — file not yet created
        init_file = path("dqs-orchestrator", "src", "orchestrator", "__init__.py")
        assert os.path.isfile(init_file), "src/orchestrator/__init__.py not found"

    def test_dqs_orchestrator_placeholder_modules_exist(self) -> None:
        """[P1] Placeholder modules (cli.py, runner.py, db.py, email.py, models.py) must exist."""
        # THIS TEST WILL FAIL — files not yet created
        required_modules = ["cli.py", "runner.py", "db.py", "email.py", "models.py"]
        base = path("dqs-orchestrator", "src", "orchestrator")
        missing = [
            m for m in required_modules
            if not os.path.isfile(os.path.join(base, m))
        ]
        assert not missing, (
            f"Missing placeholder modules in src/orchestrator/: {missing}"
        )

    def test_dqs_orchestrator_tests_directory_exists(self) -> None:
        """[P1] dqs-orchestrator must have a tests/ directory."""
        # THIS TEST WILL FAIL — directory not yet created
        assert os.path.isdir(path("dqs-orchestrator", "tests")), (
            "dqs-orchestrator/tests/ not found"
        )


# ===========================================================================
# AC2 (partial) — dqs-serve Python project structure
# ===========================================================================


class TestDqsServeStructure:
    """[P0] dqs-serve must have a valid Python/FastAPI project structure."""

    def test_dqs_serve_root_directory_exists(self) -> None:
        """[P0] dqs-serve/ directory must exist at project root."""
        # THIS TEST WILL FAIL — dqs-serve/ not yet created
        assert os.path.isdir(path("dqs-serve")), (
            "dqs-serve/ not found. Run: uv init dqs-serve"
        )

    def test_dqs_serve_pyproject_toml_exists(self) -> None:
        """[P0] dqs-serve/pyproject.toml must exist."""
        # THIS TEST WILL FAIL — pyproject.toml not yet created
        assert os.path.isfile(path("dqs-serve", "pyproject.toml")), (
            "dqs-serve/pyproject.toml not found"
        )

    def test_dqs_serve_has_fastapi_dependency(self) -> None:
        """[P0] dqs-serve must declare fastapi dependency."""
        # THIS TEST WILL FAIL — pyproject.toml not yet created
        pyproject_path = path("dqs-serve", "pyproject.toml")
        assert os.path.isfile(pyproject_path), "pyproject.toml not found"

        with open(pyproject_path, "r") as f:
            content = f.read()
        assert "fastapi" in content.lower(), (
            "dqs-serve/pyproject.toml must declare fastapi dependency"
        )

    def test_dqs_serve_has_sqlalchemy_dependency(self) -> None:
        """[P0] dqs-serve must declare sqlalchemy dependency."""
        # THIS TEST WILL FAIL — pyproject.toml not yet created
        pyproject_path = path("dqs-serve", "pyproject.toml")
        assert os.path.isfile(pyproject_path), "pyproject.toml not found"

        with open(pyproject_path, "r") as f:
            content = f.read()
        assert "sqlalchemy" in content.lower(), (
            "dqs-serve/pyproject.toml must declare sqlalchemy dependency"
        )

    def test_dqs_serve_config_directory_exists(self) -> None:
        """[P1] dqs-serve must have its own config/ directory (self-containment)."""
        # THIS TEST WILL FAIL — directory not yet created
        assert os.path.isdir(path("dqs-serve", "config")), (
            "dqs-serve/config/ not found. Each component has its own config/."
        )

    def test_dqs_serve_config_serve_yaml_exists(self) -> None:
        """[P1] dqs-serve/config/serve.yaml must exist."""
        # THIS TEST WILL FAIL — file not yet created
        assert os.path.isfile(path("dqs-serve", "config", "serve.yaml")), (
            "dqs-serve/config/serve.yaml not found"
        )

    def test_dqs_serve_src_package_structure_exists(self) -> None:
        """[P0] dqs-serve must have src/serve/ package with subdirectories."""
        # THIS TEST WILL FAIL — directories not yet created
        base = path("dqs-serve", "src", "serve")
        assert os.path.isdir(base), f"src/serve/ not found: {base}"

        required_subdirs = ["db", "routes", "services", "mcp", "schema"]
        missing = [
            d for d in required_subdirs
            if not os.path.isdir(os.path.join(base, d))
        ]
        assert not missing, (
            f"Missing subdirectories in src/serve/: {missing}"
        )

    def test_dqs_serve_main_py_exists_with_fastapi_app(self) -> None:
        """[P0] dqs-serve/src/serve/main.py must exist and define a FastAPI app."""
        # THIS TEST WILL FAIL — file not yet created
        main_file = path("dqs-serve", "src", "serve", "main.py")
        assert os.path.isfile(main_file), "src/serve/main.py not found"

        with open(main_file, "r") as f:
            content = f.read()
        assert "FastAPI" in content, (
            "main.py must import and instantiate FastAPI"
        )
        assert "/health" in content, (
            "main.py must define a /health endpoint"
        )

    def test_dqs_serve_db_placeholder_files_exist(self) -> None:
        """[P0] src/serve/db/ must have engine.py, models.py, views.py placeholders."""
        # THIS TEST WILL FAIL — files not yet created
        db_dir = path("dqs-serve", "src", "serve", "db")
        required = ["__init__.py", "engine.py", "models.py", "views.py"]
        missing = [f for f in required if not os.path.isfile(os.path.join(db_dir, f))]
        assert not missing, f"Missing files in src/serve/db/: {missing}"

    def test_dqs_serve_schema_ddl_sql_exists(self) -> None:
        """[P1] dqs-serve/src/serve/schema/ddl.sql must exist (schema DDL owner)."""
        # THIS TEST WILL FAIL — file not yet created
        assert os.path.isfile(path("dqs-serve", "src", "serve", "schema", "ddl.sql")), (
            "src/serve/schema/ddl.sql not found. "
            "dqs-serve is the schema DDL owner per architecture."
        )

    def test_dqs_serve_dockerfile_exists(self) -> None:
        """[P0] dqs-serve must have a Dockerfile for containerized deployment."""
        # THIS TEST WILL FAIL — file not yet created
        assert os.path.isfile(path("dqs-serve", "Dockerfile")), (
            "dqs-serve/Dockerfile not found"
        )

    def test_dqs_serve_tests_directory_with_conftest_exists(self) -> None:
        """[P1] dqs-serve must have tests/conftest.py for pytest fixtures."""
        # THIS TEST WILL FAIL — directory/file not yet created
        assert os.path.isdir(path("dqs-serve", "tests")), (
            "dqs-serve/tests/ not found"
        )
        assert os.path.isfile(path("dqs-serve", "tests", "conftest.py")), (
            "dqs-serve/tests/conftest.py not found"
        )


# ===========================================================================
# AC1/AC4 partial — dqs-dashboard React/TypeScript skeleton
# ===========================================================================


class TestDqsDashboardStructure:
    """[P0] dqs-dashboard must have a valid Vite/React/TypeScript project structure."""

    def test_dqs_dashboard_root_directory_exists(self) -> None:
        """[P0] dqs-dashboard/ directory must exist at project root."""
        # THIS TEST WILL FAIL — dqs-dashboard/ not yet created
        assert os.path.isdir(path("dqs-dashboard")), (
            "dqs-dashboard/ not found. "
            "Run: npm create vite@latest dqs-dashboard -- --template react-ts"
        )

    def test_dqs_dashboard_package_json_exists(self) -> None:
        """[P0] dqs-dashboard/package.json must exist."""
        # THIS TEST WILL FAIL — package.json not yet created
        assert os.path.isfile(path("dqs-dashboard", "package.json")), (
            "dqs-dashboard/package.json not found"
        )

    def test_dqs_dashboard_vite_config_exists_with_proxy(self) -> None:
        """[P0] dqs-dashboard/vite.config.ts must exist and include API proxy to port 8000."""
        # THIS TEST WILL FAIL — vite.config.ts not yet created
        vite_config = path("dqs-dashboard", "vite.config.ts")
        assert os.path.isfile(vite_config), "dqs-dashboard/vite.config.ts not found"

        with open(vite_config, "r") as f:
            content = f.read()
        assert "proxy" in content, (
            "vite.config.ts must configure a proxy server"
        )
        assert "8000" in content or "localhost:8000" in content, (
            "vite.config.ts must proxy /api to http://localhost:8000"
        )

    def test_dqs_dashboard_tsconfig_json_exists(self) -> None:
        """[P0] dqs-dashboard/tsconfig.json must exist."""
        # THIS TEST WILL FAIL — file not yet created
        assert os.path.isfile(path("dqs-dashboard", "tsconfig.json")), (
            "dqs-dashboard/tsconfig.json not found"
        )

    def test_dqs_dashboard_src_directory_structure_exists(self) -> None:
        """[P0] dqs-dashboard/src must have api/, components/, pages/, layouts/ directories."""
        # THIS TEST WILL FAIL — directories not yet created
        base = path("dqs-dashboard", "src")
        assert os.path.isdir(base), "dqs-dashboard/src/ not found"

        required_subdirs = ["api", "components", "pages", "layouts"]
        missing = [
            d for d in required_subdirs
            if not os.path.isdir(os.path.join(base, d))
        ]
        assert not missing, (
            f"Missing subdirectories in dqs-dashboard/src/: {missing}"
        )

    def test_dqs_dashboard_api_placeholder_files_exist(self) -> None:
        """[P0] src/api/ must have client.ts, queries.ts, types.ts placeholders."""
        # THIS TEST WILL FAIL — files not yet created
        api_dir = path("dqs-dashboard", "src", "api")
        required = ["client.ts", "queries.ts", "types.ts"]
        missing = [f for f in required if not os.path.isfile(os.path.join(api_dir, f))]
        assert not missing, f"Missing files in dqs-dashboard/src/api/: {missing}"

    def test_dqs_dashboard_page_components_exist(self) -> None:
        """[P1] src/pages/ must have SummaryPage.tsx, LobDetailPage.tsx, DatasetDetailPage.tsx."""
        # THIS TEST WILL FAIL — files not yet created
        pages_dir = path("dqs-dashboard", "src", "pages")
        required = ["SummaryPage.tsx", "LobDetailPage.tsx", "DatasetDetailPage.tsx"]
        missing = [f for f in required if not os.path.isfile(os.path.join(pages_dir, f))]
        assert not missing, f"Missing page components in src/pages/: {missing}"

    def test_dqs_dashboard_app_tsx_exists(self) -> None:
        """[P0] dqs-dashboard/src/App.tsx must exist."""
        # THIS TEST WILL FAIL — file not yet created
        assert os.path.isfile(path("dqs-dashboard", "src", "App.tsx")), (
            "dqs-dashboard/src/App.tsx not found"
        )


# ===========================================================================
# AC1 — docker-compose.yml service configuration
# ===========================================================================


class TestDockerComposeConfiguration:
    """[P0] docker-compose.yml must define postgres:5432, serve:8000, dashboard:5173."""

    def _load_compose(self) -> dict:
        compose_path = path("docker-compose.yml")
        assert os.path.isfile(compose_path), "docker-compose.yml not found at project root"
        with open(compose_path, "r") as f:
            return yaml.safe_load(f)

    def test_docker_compose_postgres_port_is_5432(self) -> None:
        """[P0] Postgres must be exposed on port 5432 (NOT 5433 — brownfield port change)."""
        # THIS TEST WILL FAIL — docker-compose.yml currently maps 5433:5432
        compose = self._load_compose()
        services = compose.get("services", {})
        assert "postgres" in services, "postgres service not found in docker-compose.yml"

        postgres = services["postgres"]
        ports = postgres.get("ports", [])
        port_strings = [str(p) for p in ports]
        assert any("5432:5432" in p for p in port_strings), (
            f"Postgres must be mapped '5432:5432' (external:internal). "
            f"Current ports: {ports}. "
            f"Story 1-1 requires changing from 5433:5432 to 5432:5432."
        )

    def test_docker_compose_serve_service_exists(self) -> None:
        """[P0] docker-compose.yml must include 'serve' service on port 8000."""
        # THIS TEST WILL FAIL — serve service not yet added
        compose = self._load_compose()
        services = compose.get("services", {})
        assert "serve" in services, (
            "docker-compose.yml missing 'serve' service. "
            "Must build from dqs-serve/Dockerfile and expose port 8000."
        )

    def test_docker_compose_serve_port_is_8000(self) -> None:
        """[P0] 'serve' service must be exposed on port 8000."""
        # THIS TEST WILL FAIL — serve service not yet added
        compose = self._load_compose()
        services = compose.get("services", {})
        assert "serve" in services, "serve service not found"

        serve = services["serve"]
        ports = serve.get("ports", [])
        port_strings = [str(p) for p in ports]
        assert any("8000:8000" in p for p in port_strings), (
            f"serve service must be on port 8000:8000. Current ports: {ports}"
        )

    def test_docker_compose_serve_depends_on_postgres(self) -> None:
        """[P0] 'serve' service must declare dependency on postgres."""
        # THIS TEST WILL FAIL — serve service not yet added
        compose = self._load_compose()
        services = compose.get("services", {})
        assert "serve" in services, "serve service not found"

        serve = services["serve"]
        depends = serve.get("depends_on", [])
        assert "postgres" in depends, (
            "serve service must declare 'depends_on: postgres'"
        )

    def test_docker_compose_dashboard_service_exists(self) -> None:
        """[P0] docker-compose.yml must include 'dashboard' service on port 5173."""
        # THIS TEST WILL FAIL — dashboard service not yet added
        compose = self._load_compose()
        services = compose.get("services", {})
        assert "dashboard" in services, (
            "docker-compose.yml missing 'dashboard' service. "
            "Must expose Vite dev server on port 5173."
        )

    def test_docker_compose_dashboard_port_is_5173(self) -> None:
        """[P0] 'dashboard' service must be exposed on port 5173."""
        # THIS TEST WILL FAIL — dashboard service not yet added
        compose = self._load_compose()
        services = compose.get("services", {})
        assert "dashboard" in services, "dashboard service not found"

        dashboard = services["dashboard"]
        ports = dashboard.get("ports", [])
        port_strings = [str(p) for p in ports]
        assert any("5173:5173" in p for p in port_strings), (
            f"dashboard service must be on port 5173:5173. Current ports: {ports}"
        )

    def test_docker_compose_spark_is_not_in_services(self) -> None:
        """[P1] dqs-spark must NOT be in docker-compose (runs on Spark cluster, not Docker)."""
        # This test asserts the ABSENCE of spark — it verifies a critical anti-pattern
        # It will pass once the compose file is updated (no spark service should be added)
        compose = self._load_compose()
        services = compose.get("services", {})
        service_names = list(services.keys())
        spark_services = [s for s in service_names if "spark" in s.lower()]
        assert not spark_services, (
            f"dqs-spark must NOT be in docker-compose. "
            f"Found spark-related services: {spark_services}. "
            f"Spark runs on a cluster, not in local Docker."
        )

    def test_docker_compose_orchestrator_is_not_in_services(self) -> None:
        """[P1] dqs-orchestrator must NOT be in docker-compose (runs on scheduling server)."""
        # This test asserts the ABSENCE of orchestrator — verifies anti-pattern
        compose = self._load_compose()
        services = compose.get("services", {})
        service_names = list(services.keys())
        orch_services = [s for s in service_names if "orchestrat" in s.lower()]
        assert not orch_services, (
            f"dqs-orchestrator must NOT be in docker-compose. "
            f"Found: {orch_services}. "
            f"Orchestrator runs on scheduling server, not in Docker."
        )


# ===========================================================================
# AC4 — Self-containment: no shared root-level config
# ===========================================================================


class TestSelfContainmentNoSharedResources:
    """[P1] Each component must have its own config/ — no shared root-level config."""

    def test_no_shared_config_directory_at_root(self) -> None:
        """[P1] There must NOT be a shared config/ directory at the project root."""
        # This is an anti-pattern check — it should NOT exist
        # Passes if there's no root config/ (but may fail if someone accidentally creates one)
        shared_config = path("config")
        assert not os.path.isdir(shared_config), (
            "Shared config/ directory found at project root. "
            "NEVER create shared config/ — each component has its own config/. "
            "This violates self-containment principles."
        )

    def test_no_shared_requirements_txt_at_root(self) -> None:
        """[P1] There must NOT be a shared requirements.txt at the project root."""
        # Anti-pattern: shared Python deps file
        shared_req = path("requirements.txt")
        assert not os.path.isfile(shared_req), (
            "Shared requirements.txt found at project root. "
            "Use uv per-component (pyproject.toml). Never shared Python deps."
        )

    def test_each_new_component_has_own_config_directory(self) -> None:
        """[P1] dqs-spark, dqs-serve, dqs-orchestrator must each have config/ directories."""
        # THIS TEST WILL FAIL — component directories not yet created
        components = ["dqs-spark", "dqs-serve", "dqs-orchestrator"]
        missing = [
            comp for comp in components
            if not os.path.isdir(path(comp, "config"))
        ]
        assert not missing, (
            f"Components missing own config/ directory: {missing}. "
            f"Each component must be fully self-contained."
        )

    def test_prototype_directories_still_exist_and_untouched(self) -> None:
        """[P1] Prototype directories (spark-job/, serve-api/, db/) must still exist (brownfield)."""
        # These should remain untouched — brownfield coexistence
        # This test will pass if they haven't been deleted
        assert os.path.isdir(path("spark-job")), (
            "spark-job/ prototype directory is missing. Do not delete prototype dirs."
        )
        assert os.path.isdir(path("serve-api")), (
            "serve-api/ prototype directory is missing. Do not delete prototype dirs."
        )

    def test_dqs_dashboard_has_own_package_json_not_shared(self) -> None:
        """[P1] dqs-dashboard must have its own package.json, not a root-level one."""
        # THIS TEST WILL FAIL — dqs-dashboard not yet created
        # Verify dashboard has its own package.json
        assert os.path.isfile(path("dqs-dashboard", "package.json")), (
            "dqs-dashboard/package.json not found. "
            "Dashboard must be self-contained with its own package.json."
        )

        # Root-level package.json is allowed (if it exists for tooling) but
        # it must not be the only one
        dashboard_pkg = path("dqs-dashboard", "package.json")
        assert os.path.isfile(dashboard_pkg), (
            "dqs-dashboard must have its own package.json"
        )
